export const skills = [
	// Development
	"Web Development",
	"Frontend Development",
	"Backend Development",
	"Full Stack Development",
	"JavaScript",
	"TypeScript",
	"HTML",
	"CSS",
	"React",
	"Next.js",
	"Vue.js",
	"Angular",
	"Node.js",
	"Express.js",
	"NestJS",
	"PHP",
	"Laravel",
	"Python",
	"Django",
	"Flask",
	"Ruby on Rails",
	"Java",
	"Spring Boot",
	"C#",
	".NET",
	"REST API Development",
	"GraphQL",
	"WebSockets",
	"Microservices",
	"API Integration",

	// Mobile Development
	"Mobile App Development",
	"iOS Development",
	"Android Development",
	"React Native",
	"Flutter",
	"Swift",
	"Kotlin",
	"Hybrid App Development",

	// Databases
	"MySQL",
	"PostgreSQL",
	"MongoDB",
	"Firebase",
	"Redis",
	"Database Design",
	"Database Optimization",

	// DevOps & Cloud
	"DevOps",
	"Docker",
	"Kubernetes",
	"AWS",
	"Google Cloud",
	"Microsoft Azure",
	"CI/CD",
	"Linux Administration",
	"Server Management",
	"Nginx",
	"Apache",

	// Design & Creative
	"UI Design",
	"UX Design",
	"Web Design",
	"Graphic Design",
	"Logo Design",
	"Brand Identity",
	"Figma",
	"Adobe XD",
	"Photoshop",
	"Illustrator",
	"Canva",
	"Motion Graphics",
	"Video Editing",
	"After Effects",
	"Premiere Pro",

	// Writing & Content
	"Content Writing",
	"Copywriting",
	"SEO Writing",
	"Technical Writing",
	"Blog Writing",
	"Ghostwriting",
	"Creative Writing",
	"Proofreading",
	"Editing",
	"Resume Writing",

	// Marketing & SEO
	"Digital Marketing",
	"SEO",
	"On-Page SEO",
	"Off-Page SEO",
	"Keyword Research",
	"Google Ads",
	"Facebook Ads",
	"Social Media Marketing",
	"Email Marketing",
	"Marketing Strategy",
	"Conversion Rate Optimization",
	"Affiliate Marketing",

	// E-commerce
	"E-commerce Development",
	"Shopify",
	"WooCommerce",
	"Magento",
	"Product Listing",
	"Dropshipping",
	"Amazon FBA",
	"Etsy Store Setup",

	// Data & AI
	"Data Analysis",
	"Data Visualization",
	"Power BI",
	"Tableau",
	"Excel",
	"Google Sheets",
	"SQL",
	"Machine Learning",
	"Deep Learning",
	"Artificial Intelligence",
	"NLP",
	"Computer Vision",
	"Data Science",

	// QA & Testing
	"Software Testing",
	"Manual Testing",
	"Automation Testing",
	"Selenium",
	"Cypress",
	"Jest",
	"Unit Testing",
	"Integration Testing",

	// Business & Support
	"Virtual Assistant",
	"Customer Support",
	"Technical Support",
	"Project Management",
	"Agile",
	"Scrum",
	"Product Management",
	"Business Analysis",

	// No-Code & CMS
	"WordPress",
	"Webflow",
	"Wix",
	"Squarespace",
	"Bubble",
	"No-Code Development",
	"Low-Code Development",

	// Other
	"Blockchain Development",
	"Smart Contracts",
	"Solidity",
	"Web3",
	"Cybersecurity",
	"Penetration Testing",
	"Ethical Hacking",
];
